FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

RUN useradd -ms /bin/bash appuser
USER appuser

COPY build/libs/app.jar app.jar

EXPOSE 8080

ENV JAVA_OPTS=""

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]