INSERT INTO `questions` (competency_type_id, content, guidance_message)
VALUES ((SELECT id FROM competency_types WHERE type_name = '팀워크'),
        '공동의 목표를 가진 팀 활동 중 가장 기억에 남는 경험을 한 가지 선택하여, 팀에서의 역할과 기여, 성과를 구체적으로 작성해 주세요.', '팀워크를 발휘했던 사례'),
       ((SELECT id FROM competency_types WHERE type_name = '팀워크'),
        '여러 사람과 함께 프로젝트를 수행하며 팀워크를 발휘했던 사례를 구체적으로 작성해 주십시오.', '구성원 간 협력이 잘 이루어진 사례'),
       ((SELECT id FROM competency_types WHERE type_name = '팀워크'),
        '살아오면서 경험한 팀 프로젝트 중, 구성원 간 협력이 가장 잘 이루어졌다고 생각하는 사례와 그 이유를 설명해 주세요.', '팀 활동 중 가장 기억에 남는 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '협업'),
        '다른 사람들과 협업하여 공동의 목표를 달성한 경험과, 해당 과정에서 본인은 어떠한 역할을 수행하였는지 설명해 주세요.', '유관 부서/외부와의 협업 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '협업'),
        '유관 부서 또는 외부 이해관계자와의 협업을 통해 문제를 해결하거나 성과를 낸 경험을 구체적으로 서술해 주세요.', '다른 사람들과 협업하여 노력했던 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '협업'),
        '공동의 목표를 달성하기 위해 다른 사람들과 힘을 합쳐 노력했던 경험을 구체적으로 기술하고, 그 경험을 통해 배운 점을 작성해 주세요.', '공동의 목표를 달성한 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '커뮤니케이션'),
        '본인이 생각하는 커뮤니케이션 능력이란 무엇인지 정의하고, 이를 발휘하여 긍정적인 결과를 이끌어낸 경험을 작성해 주세요.', '커뮤니케이션 능력'),
       ((SELECT id FROM competency_types WHERE type_name = '커뮤니케이션'),
        '업무(또는 학업) 수행 중 이해관계자와의 원활한 소통을 통해 문제를 예방하거나 해결한 경험을 구체적으로 작성해 주십시오.', '이해관계자와의 소통 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '커뮤니케이션'),
        '전달이 어려운 내용을 상대가 이해할 수 있도록 설명해야 했던 경험과, 이를 위해 활용한 커뮤니케이션 방식에 대해 작성해 주세요.', '어려운 내용을 설명한 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '갈등해결'),
        '팀 프로젝트나 단체 활동 중 의견 충돌 또는 갈등이 발생했던 경험을 구체적으로 서술하고, 이를 어떻게 해결했는지, 그 결과 무엇을 얻었는지 작성해 주세요.', '갈등 조정/중재 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '갈등해결'),
        '동료와의 관계에서 갈등이 발생했을 때, 본인이 갈등을 인식하고 해결하기 위해 취한 행동과 그 이후 변화를 대해 서술해 주세요.', '의견 충돌/갈등 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '갈등해결'),
        '조직 내 갈등 상황을 조정하거나 중재한 경험이 있다면, 상황·갈등 원인·해결 과정·성과를 중심으로 작성해 주십시오.', '동료와의 갈등 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '리더십'),
        '본인이 생각하는 리더십의 의미를 정의하고, 리더십을 발휘하여 성공 또는 실패한 경험이 있다면 기술하시오.', '리더십 성공/실패 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '리더십'),
        '팀 리더로서 목표를 설정하고 구성원들을 이끌어 성과를 낸 경험을 작성해 주세요. (목표, 역할 분담, 동기부여, 결과 포함)', '팀 리더로서의 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '리더십'),
        '공식적인 직책 유무와 상관없이, 주변 사람들에게 긍정적인 영향을 미친 리더십 경험을 상황 중심으로 서술해 주세요.', '긍정적인 리더십 발휘 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '문제해결'),
        '최근 겪은 어려운 문제를 해결한 경험을 구체적으로 설명해 주십시오. ① 상황, ② 어려움, ③ 해결 방법, ④ 결과 및 느낀 점을 포함해 주세요.', '어려운 문제 해결 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '문제해결'),
        '업무 또는 학업, 프로젝트 수행 중 직면했던 가장 어려운 문제 상황을 하나 제시하고, 이를 해결하기 위해 스스로 분석하고 의사결정하여 실행한 과정을 단계별로 작성해 주세요.',
        '가장 어려웠던 문제 극복 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '문제해결'),
        '반복되는 실패에도 불구하고 끝까지 문제 해결을 시도해 성과를 낸 경험이 있다면 작성해 주세요.', '반복 실패 후 성과를 낸 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '분석력'),
        '복잡한 상황에서 핵심 원인을 분석하여 문제를 해결한 경험을 구체적으로 작성해 주세요.', '문제 핵심 원인 분석 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '분석력'),
        '데이터나 자료를 체계적으로 분석하여 더 나은 의사결정을 이끌어낸 사례를 설명해 주십시오.', '데이터 분석으로 의사결정한 사례'),
       ((SELECT id FROM competency_types WHERE type_name = '분석력'),
        '충분한 정보가 없거나 애매한 상황에서, 스스로 정보를 수집·정리·분석해 방향을 정했던 경험을 서술해 주세요.', '정보 수집·분석 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '의사결정'),
        '여러 대안 중에서 어려운 선택을 해야 했던 경험을 제시하고, 선택 기준과 의사결정 과정을 상세히 작성해 주세요.', '선택 기준 수립과 의사결정 과정'),
       ((SELECT id FROM competency_types WHERE type_name = '의사결정'),
        '충분한 시간이 없는 상황에서 빠르게 의사결정을 내려야 했던 경험과, 그에 따른 결과를 작성해 주십시오.', '빠른 의사결정 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '의사결정'),
        '팀 내에서 의견이 갈리는 상황에서, 본인이 중심이 되어 방향을 결정하고 추진한 경험을 서술해 주세요.', '팀 내 방향 결정 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '기획력'),
        '새로운 활동이나 프로젝트를 기획하여 실행한 경험을 작성해 주세요. (기획 배경, 목표, 실행 과정, 결과 포함)', '새로운 활동/프로젝트 기획 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '기획력'),
        '기존 방식을 개선하기 위해 본인이 주도적으로 아이디어를 내고 기획해 실행한 경험을 구체적으로 서술해 주십시오.', '기존 방식 개선 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '기획력'),
        '제한된 자원 내에서 최대 효과를 내기 위해 계획을 수립하고 수행한 경험을 작성해 주세요.', '제한된 자원 내 계획 수립 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '창의성'),
        '고정관념을 깨는 새로운 아이디어나 접근법으로 문제를 해결한 경험을 구체적으로 작성해 주세요.', '새로운 아이디어로 문제 해결 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '창의성'),
        '주변에서 모두가 당연하게 받아들이던 방식을 창의적으로 바꾸어 성과를 낸 사례가 있다면 설명해 주십시오.', '기존 방식을 창의적으로 바꾼 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '창의성'),
        '제안한 아이디어가 처음에는 반대나 무시를 받았지만, 끝까지 설득하여 실행된 경험이 있다면 서술해 주세요.', '반대를 극복하고 아이디어 실행한 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '실행력'),
        '계획에 그치지 않고 실제로 행동으로 옮겨 성과를 만든 경험에 대해, 구체적인 행동과 결과를 중심으로 작성해 주세요.', '계획을 실제 행동으로 옮겨 성과를 낸 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '실행력'), '주어진 업무 외에 스스로 필요성을 느껴 주도적으로 실행한 경험을 서술해 주십시오.',
        '주도적으로 실행한 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '실행력'),
        '짧은 시간 안에 많은 일을 처리해야 했던 상황에서, 어떻게 우선순위를 정하고 실행하여 마무리했는지 작성해 주세요.', '짧은 시간 내 많은 업무 처리 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '책임감'),
        '막중한 책임이 따르는 역할을 맡았던 경험을 제시하고, 책임을 다하기 위해 어떤 노력을 했는지 구체적으로 기술해 주십시오.', '막중한 책임을 맡았던 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '책임감'),
        '실수나 문제 발생 시, 책임을 회피하지 않고 해결을 위해 행동한 경험을 작성해 주세요.', '실수/문제 발생 시 해결한 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '책임감'),
        '책임감을 가지고 신속하게 행동하여 성과를 냈던 경험에 대해 서술하여 주시기 바랍니다.', '책임감 있게 성과를 낸 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '적응력'), '새로운 환경이나 방식에 빠르게 적응해야 했던 경험을 구체적으로 작성해 주세요.',
        '새로운 환경 적응 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '적응력'),
        '예상치 못한 변화나 변수로 계획을 수정해야 했던 상황에서, 어떻게 대응하고 적응했는지 서술해 주십시오.', '예상치 못한 변화 대응 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '적응력'),
        '익숙하지 않은 업무나 역할을 맡았을 때, 본인이 배워 가며 적응해 간 과정을 작성해 주세요.', '익숙하지 않은 역할 적응 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '학습능력'), '스스로 목표를 세우고 학습하여 역량을 향상시킨 경험을 작성해 주세요.',
        '스스로 학습하여 역량 향상 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '학습능력'),
        '단기간에 새로운 지식이나 기술을 습득해야 했던 경험과, 이를 위해 사용한 학습 방법을 구체적으로 서술해 주십시오.', '단기간 지식/기술 습득 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '학습능력'),
        '실패나 부족한 성과를 계기로, 어떤 점을 학습·보완했는지 구체적으로 설명해 주세요.', '실패 후 학습·보완한 경험'),

       ((SELECT id FROM competency_types WHERE type_name = '목표지향'),
        '자발적으로 최고 수준의 목표를 세우고 끈질기게 성취한 경험에 대해 서술해 주십시오.', '최고 수준 목표 성취 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '목표지향'), '뚜렷한 목표를 위해 새롭게 시도하고 도전한 경험에 대해 작성해 주세요.',
        '목표를 위해 도전한 경험'),
       ((SELECT id FROM competency_types WHERE type_name = '목표지향'),
        '도전적인 목표를 세우고 성취하기 위해 끈질기게 노력한 경험에 대해 서술해 주세요. (목표·수립 과정·어려움·노력·결과·느낀 점 포함)', '도전적 목표 달성 경험');
