-- MySQL Script generated by MySQL Workbench
-- Thu Jan 22 17:05:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `episode_db_v0`.`occupation`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`occupation` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(15) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `episode_db_v0`.`job`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`job` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(15) NOT NULL,
    `occupation_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
    INDEX `job2occupation_idx` (`occupation_id` ASC) VISIBLE,
    CONSTRAINT `job2occupation`
    FOREIGN KEY (`occupation_id`)
    REFERENCES `episode_db_v0`.`occupation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `episode_db_v0`.`users`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`users` (
   `kakao_id` BIGINT NOT NULL,
   `job_id` INT NOT NULL,
   `nickname` VARCHAR(45) NOT NULL,
    `has_watched_feature_guide` TINYINT NOT NULL,
    PRIMARY KEY (`kakao_id`),
    INDEX `user2job_idx` (`job_id` ASC) VISIBLE,
    CONSTRAINT `user2job`
    FOREIGN KEY (`job_id`)
    REFERENCES `episode_db_v0`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `episode_db_v0`.`competency_type`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`competency_type` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `type_name` VARCHAR(50) NOT NULL,
    `category` ENUM("협업/커뮤니케이션 역량", "문제해결/사고 역량", "실행/성장 역량") NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `episode_db_v0`.`question`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`question` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `competency_type_id` INT NOT NULL,
    `job_id` INT NOT NULL,
    `content` VARCHAR(200) NOT NULL,
    `guidance_message` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `question2competency_type_idx` (`competency_type_id` ASC) VISIBLE,
    INDEX `question2job_idx` (`job_id` ASC) VISIBLE,
    CONSTRAINT `question2competency_type`
    FOREIGN KEY (`competency_type_id`)
    REFERENCES `episode_db_v0`.`competency_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `question2job`
    FOREIGN KEY (`job_id`)
    REFERENCES `episode_db_v0`.`job` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `episode_db_v0`.`mindmap`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`mindmap` (
    `id` BINARY(16) NOT NULL,
    `created_time` DATETIME NOT NULL,
    `is_shared` TINYINT NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `episode_db_v0`.`episode`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`episode` (
    `node_id` INT NOT NULL COMMENT '개인 마인드맵의 에피소드 노드만\n',
    `user_id` BIGINT NOT NULL,
    `mindmap_id` BINARY(16) NOT NULL,
    `situation` VARCHAR(200) NULL,
    `task` VARCHAR(200) NULL,
    `action` VARCHAR(200) NULL,
    `result` VARCHAR(200) NULL,
    `content` VARCHAR(100) NULL,
    PRIMARY KEY (`node_id`, `user_id`),
    INDEX `experience2user_idx` (`user_id` ASC) VISIBLE,
    INDEX `experience2mindmap_idx` (`mindmap_id` ASC) VISIBLE,
    CONSTRAINT `experience2user`
    FOREIGN KEY (`user_id`)
    REFERENCES `episode_db_v0`.`users` (`kakao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `experience2mindmap`
    FOREIGN KEY (`mindmap_id`)
    REFERENCES `episode_db_v0`.`mindmap` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `episode_db_v0`.`user2mindmap`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`user2mindmap` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `mindmap_id` BINARY(16) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `2mindmap_idx` (`mindmap_id` ASC) VISIBLE,
    INDEX `2user_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `2mindmap`
    FOREIGN KEY (`mindmap_id`)
    REFERENCES `episode_db_v0`.`mindmap` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `2user`
    FOREIGN KEY (`user_id`)
    REFERENCES `episode_db_v0`.`users` (`kakao_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `episode_db_v0`.`diagnosis_result`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`diagnosis_result` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `job_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `diagnosis_result2job_idx` (`job_id` ASC) VISIBLE,
    INDEX `diagnosis_result2user_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `diagnosis_result2job`
    FOREIGN KEY (`job_id`)
    REFERENCES `episode_db_v0`.`job` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `diagnosis_result2user`
    FOREIGN KEY (`user_id`)
    REFERENCES `episode_db_v0`.`users` (`kakao_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `episode_db_v0`.`diagnosis2question`
-- -----------------------------------------------------
CREATE TABLE `episode_db_v0`.`diagnosis2question` (
    `id`                  INT NOT NULL AUTO_INCREMENT,
    `diagnosis_result_id` INT NOT NULL,
    `question_id`         INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `2question_idx` (`question_id` ASC) VISIBLE,
    INDEX `2diagnosis_result_idx` (`diagnosis_result_id` ASC) VISIBLE,
    CONSTRAINT `2question`
    FOREIGN KEY (`question_id`)
    REFERENCES `episode_db_v0`.`question` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `diagnosis_result`
    FOREIGN KEY (`diagnosis_result_id`)
    REFERENCES `episode_db_v0`.`diagnosis_result` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_unicode_ci;
