ALTER TABLE mindmap
    MODIFY updated_at DATETIME(6) NOT NULL
    DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6);

ALTER TABLE mindmap
    MODIFY created_at DATETIME(6) NOT NULL
    DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE episode
    MODIFY created_at DATETIME(6) NOT NULL
    DEFAULT CURRENT_TIMESTAMP(6);