ALTER TABLE mindmap
    ALTER COLUMN updated_at TIMESTAMP(6) NOT NULL
    DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6);

ALTER TABLE mindmap
    ALTER COLUMN created_at TIMESTAMP(6) NOT NULL
    DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE episode
    ALTER COLUMN created_at TIMESTAMP(6) NOT NULL
    DEFAULT CURRENT_TIMESTAMP(6);
