ALTER TABLE mindmap RENAME COLUMN created_time TO created_at;
ALTER TABLE mindmap ALTER COLUMN created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE mindmap ADD COLUMN updated_at TIMESTAMP(6);

UPDATE mindmap SET updated_at = created_at;

ALTER TABLE mindmap ALTER COLUMN updated_at TIMESTAMP(6) NOT NULL
    DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);


ALTER TABLE episode ADD COLUMN created_at TIMESTAMP(6);

UPDATE episode SET created_at = CURRENT_TIMESTAMP(6);

ALTER TABLE episode ALTER COLUMN created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
